version: "3"
services:
  mysql:
    image: "mysql:latest"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: mysql
  application:
    image: "registry/shopping-cart:latest"
    container_name: app_main
    ports:
      - "8082:8070"
